//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agent_WebForm_Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.Configuration;
    using System.Data.SqlClient;

    public partial class AgentCart
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AgentCart()
        {
            this.AgentCartDetails = new HashSet<AgentCartDetail>();
        }
    
        public string CartID { get; set; }
        public string AgentID { get; set; }
        public Nullable<decimal> TotalBill { get; set; }
        public Nullable<bool> CartDeleted { get; set; }
    
        public virtual Agent Agent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AgentCartDetail> AgentCartDetails { get; set; }

        public AgentCart SelectAgentCartQuery(string agentId)
        {
            using (SqlConnection conn = new SqlConnection(ConfigurationManager.ConnectionStrings["DBConn"].ToString()))
            {
                conn.Open();
                string sql = "select * from AgentCart where AgentID = '" + agentId + "'";
                SqlCommand cmd = new SqlCommand(sql, conn);

                AgentCart res = new AgentCart();
                SqlDataReader dr = cmd.ExecuteReader();
                while (dr.Read())
                {
                    res.CartID = dr["CartID"].ToString();
                    res.AgentID = dr["AgentID"].ToString();
                    res.TotalBill = Convert.ToDecimal(dr["TotalBill"].ToString());
                }
                conn.Close();
                return res;
            }
        }

        public void AddCartQuery(string cartID, string agentId)
        {
            using (SqlConnection conn = new SqlConnection(ConfigurationManager.ConnectionStrings["DBConn"].ToString()))
            {
                conn.Open();
                string sql = "insert into AgentCart values ('" +
                    cartID +
                    "', '" + agentId +
                    "', " + 0 +
                    ", " + 0 + ")";
                SqlCommand cmd = new SqlCommand(sql, conn);
                cmd.ExecuteNonQuery();
            }
        }

        private string GetCartDesc()
        {
            using (SqlConnection conn = new SqlConnection(ConfigurationManager.ConnectionStrings["DBConn"].ToString()))
            {
                conn.Open();
                string sql = "select top 1 CartID from AgentCart order by CartID desc";
                SqlCommand cmd = new SqlCommand(sql, conn);

                SqlDataReader dr = cmd.ExecuteReader();
                string res = "";
                while (dr.Read())
                {
                    res = dr["CartID"].ToString();
                }
                conn.Close();
                return res;
            }
        }

        public string GetNewCartID()
        {
            string res = GetCartDesc();
            if (res != null && !res.Equals(""))
            {
                int order = int.Parse(res.Substring(4)) + 1;
                if (order < 10)
                {
                    res = "ACTD00000" + order.ToString();
                }
                else if (order < 100)
                {
                    res = "ACTD0000" + order.ToString();
                }
                else if (order < 1000)
                {
                    res = "ACTD000" + order.ToString();
                }
                else if (order < 10000)
                {
                    res = "ACTD00" + order.ToString();
                }
                else if (order < 100000)
                {
                    res = "ACTD0" + order.ToString();
                }
                else
                {
                    res = "ACTD" + order.ToString();
                }
                return res;
            }
            else
            {
                return "ACTD000001";
            }
        }
    }
}
