//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agent_WebForm_Project.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DistributorDBEntities : DbContext
    {
        public DistributorDBEntities()
            : base("name=DistributorDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C_Order> C_Order { get; set; }
        public virtual DbSet<C_User> C_User { get; set; }
        public virtual DbSet<Agent> Agents { get; set; }
        public virtual DbSet<AgentAccount> AgentAccounts { get; set; }
        public virtual DbSet<AgentCart> AgentCarts { get; set; }
        public virtual DbSet<AgentCartDetail> AgentCartDetails { get; set; }
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<UserAccount> UserAccounts { get; set; }
    }
}
